apiVersion: v1
kind: Service
metadata:
  name: ado-pool-cleanup
spec:
  selector:
    app: ado-pool-cleanup
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-pool-cleanup
  namespace: ado-pool-cleanup
  labels:
    app: ado-pool-cleanup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-pool-cleanup
  template:
    metadata:
      labels:
        app: ado-pool-cleanup
    spec:
      containers:
      - name: ado-pool-cleanup
        image: ataylorregistry.azurecr.io/ado-pool-cleaner:#{ImageTag}#
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: atayloracr
      nodeSelector:
          "beta.kubernetes.io/os": linux
